name: Pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: acessar diretorio
        run: cd TSAT    
      - name: install dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -V pytest
          pip pip install -r requirements.txt 

      -  name: Run pytest
         run: pythom -m pytest    